export { Table1 } from "./table1";
export { Table2 } from "./table2";
export { Table3 } from "./table3";
export { Table4 } from "./table4";
export { Table5 } from "./table5";
export { Table6 } from "./table6";
export { Table7 } from "./table7";
export { Table8 } from "./table8";
export { Table9 } from "./table9";